const tintColorLight = "#0a7ea4";
const tintColorDark = "#fff";

export const Colors = {
  light: {
    text: "#11181C",
    onboardText: "#9c9c9c",
    background: "#fff",
    tint: tintColorLight,
    icon: "#388E3C",
    tabIconDefault: "#687076",
    tabIconSelected: tintColorLight,
    tabBarBackground: "#008080",
    tabIconColor: "#000",
    activeBarOnboard: "#000",
    InactiveBarOnboard: "#9c9c9c",
    statusBar: "light",
    drawerActiveItemBackground: "#151718",
    drawerActiveItemText: "#fff",
    tintText: "#808080",
    tintBackground: "#A9A9A9",
    cardBackground: "#F5F6F8",
    inputKeyboard: "#808080",
    notificationSheetBackground: "#808080",
  },
  dark: {
    text: "#ECEDEE",
    onboardText: "#ffd200",
    background: "#151718",
    tint: tintColorDark,
    icon: "#00FFFF",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: tintColorDark,
    tabBarBackground: "#030608",
    tabIconColor: "#00FFFF",
    activeBarOnboard: "#ffd200",
    InactiveBarOnboard: "#9c9c9c",
    statusBar: "dark",
    drawerActiveItemBackground: "#E5E5E5",
    drawerActiveItemText: "#000",
    tintText: "#808080",
    tintBackground: "#A9A9A9",
    cardBackground: "#1C1E1F",
    inputKeyboard: "#1e2021",
    notificationSheetBackground: "#1e2021",
  },
};
